// <auto-generated />
using GlassLewis.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlassLewis.Infrastructure.Migrations
{
    [DbContext(typeof(GlassLewisDbContext))]
    [Migration("20220722183306_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GlassLewis.Core.GlassLewis.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Exchange = "NASDAQ",
                            ISIN = "US0378331005",
                            Name = "Apple Inc.",
                            Ticker = "AAPL",
                            Website = "http://www.apple.com"
                        },
                        new
                        {
                            Id = 2,
                            Exchange = "Pink Sheets",
                            ISIN = "US1104193065",
                            Name = "British Airways Plc.",
                            Ticker = "BAIRY",
                            Website = ""
                        },
                        new
                        {
                            Id = 3,
                            Exchange = "Euronext Amsterdam",
                            ISIN = "NL0000009165",
                            Name = "Heineken NV",
                            Ticker = "HEIA",
                            Website = ""
                        },
                        new
                        {
                            Id = 4,
                            Exchange = "Tokyo Stock Exchange",
                            ISIN = "JP3866800000",
                            Name = "Panasonic Corp",
                            Ticker = "6752",
                            Website = "http://www.panasonic.co.jp"
                        },
                        new
                        {
                            Id = 5,
                            Exchange = "Deutsche Börse",
                            ISIN = "DE000PAH0038",
                            Name = "Porsche Automobil",
                            Ticker = "PAH3",
                            Website = "https://www.porsche.com/"
                        });
                });

            modelBuilder.Entity("GlassLewis.Core.GlassLewis.Models.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "User1@abc.com",
                            Password = "123456"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "User2@abc.com",
                            Password = "123456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
